Optimal use with modern Nim
jangko/freetype pull request #2
Opened 2021-08-15 06:09 UTC by momeemt

Thank you for developing the freetype wrapper.
I found a few things that need to be fixed in order to use this wrapper comfortably with the current Nim.

1. The syntax of Nimble has changed.
1. The structure that the Nimble Package should take has changed.
1. The csize type has been deprecated.

These fixes make disruptive changes, so please check carefully!

2021-08-16 05:52 UTC, jangko requested changes

2021-08-16 05:52 UTC, jangko commented on freetype.nimble
> -name          = "freetype"
You can use `packageName` to replace `name`.

2021-08-16 05:52 UTC, jangko commented on freetype.nimble
> +srcDir        = "src"
please keep the directory structure as is. I don't like `src/freetype`, a simple `freetype` is ok.

2021-08-16 05:52 UTC, jangko commented on src/freetype.nim
> +import freetype/[freetype, ftadvanc, ftautoh, ftbbox, ftbdf, ftbitmap, ftbzip2, ftcache, ftcffdrv, ftcid, fterrdef, ftfntfmt, ftgasp, ftglyph, ftgxval, ftgzip, ftimage, ftimport, ftincrem, ftlcdfil,
this file should be put in root directory.

2021-08-16 05:52 UTC, jangko commented on src/freetype/ftbbox.nim
> -import freetype, fttypes, ftimage
good catch. nice.

2023-08-04 03:20 UTC, neroist commented
@jangko don't you think you should close this? Its been a year.

2023-08-04 03:55 UTC, jangko commented
closing in favor of #4

2023-08-04 03:55 UTC, closed without merging